Reorg, simplify loader, enhance data fidelity

diff --git a/rc b/rc
--- a/rc
+++ b/rc
@@ -1,66 +1,99 @@
-#!/bin/sh
+# Purposefully no shebang.
 
-SHELL_CONF_DIR="$HOME/.shell"
+# Mark that we're during init
+export __SHELL_CONF_INIT=true
 
-if [[ -z "$CURRENT_SHELL" ]]; then
-    echo "CURRENT_SHELL is not set!" >&2
-fi
-: ${CURRENT_SHELL:="unknown_shell"}
+: "${SHELL_CONF_DIR:="$HOME/.shell"}"
 
-declare -l SYSTEM="$(uname -s)"
-[[ -n "$SYSTEM" ]] || SYSTEM="unknown_system"
+[[ ! -f "$SHELL_CONF_DIR/debug" ]] || DEBUG=true
+[[ ! -f "$SHELL_CONF_DIR/verbose" ]] || set -v
+[[ ! -f "$SHELL_CONF_DIR/trace" ]] || set -xv
 
-##
-## init
-##
+. "$SHELL_CONF_DIR/lib.sh"
 
--shell-conf-files() {
-    local delim='::'
-    local -a files
-    local d f
-    for d in "$SHELL_CONF_DIR/"{"",{"$SYSTEM"{,"-$CURRENT_SHELL"},"$CURRENT_SHELL"}-}{rc,completion,aliases}.d; do
-        # Can't rely on nullglob in case we're not on bash/zsh
-        [[ -d "$d" ]] || continue
+shellconf-validate-plugin-type() {
+    # Returns failure if plugin path should be used for this system and shell.
+    # This is done via simple extension matching.
+    local fn fext
 
-        for f in "$d"/*; do
-            # Can't rely on nullglob in case we're not on bash/zsh
-            [[ -f "$f" || -h "$f" ]] || continue
+    # Allow us to recurse if we should recheck alter a transform
+    if [[ "$1" == "__revalidate__" ]]; then
+        shift
+        fn="$1"
+        fext="$2"
+    else
+        fn="${1##*/}"
+        fext="${fn#*.}"
+    fi
 
-            # Only exec if the exec bit is set
-            [[ -x "$f" ]] || continue
-
-            files+=("${f##*/}${delim}$f")
-        done
-    done
-
-	local -a sorted_files
-	IFS=$'\n' sorted_files=($(sort <<<"${files[*]}"))
-
-	ret=()
-	for f in "${sorted_files[@]}"; do
-        [[ -n "$f" ]] || continue
-
-		f="${f#*$delim}"
-		ret+=("$f")
-	done
+    case "$fext" in
+        $SYSTEM|$CURRENT_SHELL|$SYSTEM.$CURRENT_SHELL)
+            return $?
+            ;;
+        *.sh)
+            shellconf-validate-plugin-type __revalidate__ "$fn" "${fext%.sh}"
+            return $?
+            ;;
+        sh.*)
+            shellconf-validate-plugin-type __revalidate__ "$fn" "${fext#sh.}"
+            return $?
+            ;;
+        *)
+            if [[ "$fn" = *.* ]]; then
+                # If there's any extension at all and we haven't okd by now,
+                # it's a no-go.
+                return 1
+            else
+                # If there's no extension that's just fine.
+                return 0
+            fi
+            ;;
+    esac
+    error "Somehow got past the wildcard case in $0"
+    return 1
 }
 
--shell-conf-init() {
-    if [[ ! -d "$SHELL_CONF_DIR" ]]; then
-        echo "SHELL_CONF_DIR=\"$SHELL_CONF_DIR\" does not exist!" >&2
+
+shellconf-plugins() {
+    local d f
+
+    for d in "$SHELL_CONF_DIR"/{rc,completion,aliases}.d; do
+        [ -d "$d" ] || continue
+
+        for f in "$d"/*; do
+            # Ensure it's the right kind of plugin
+            shellconf-validate-plugin-type "$f" || continue
+
+            # Only files or symlinks thanks
+            [ -f "$f" ] || [  -h "$f" ] || continue
+
+            # Only exec if the exec bit is set
+            [ -x "$f" ] || continue
+
+            echo "$f"
+            ret+=("$f")
+        done
+    done
+}
+
+shellconf-init() {
+    debug "ShellConf: Init"
+
+    if [ ! -d "$SHELL_CONF_DIR" ]; then
+        error "SHELL_CONF_DIR=\"$SHELL_CONF_DIR\" does not exist"
         return 1
     fi
 
-    echo "ShellConf: Init" >&2
-    ret=()
-    -shell-conf-files
+    local f ret=()
+    shellconf-plugins >/dev/null
     for f in "${ret[@]}"; do
-        f_rel="${f##$HOME/.shell/}"
-        echo "-- ${f_rel##*/}: $f_rel" >&2
+        f_rel="${f#$SHELL_CONF_DIR/}"
+        debug "-- $f_rel"
         . "$f"
     done
-    unset ret f f_rel
 }
 
--shell-conf-init
+shellconf-init
+unset __SHELL_CONF_INIT
 
+# vim: set ts=4 sw=4 tw=0 ft=sh et :
